### ISSUE TITLE
php のソースが必要なのでしょうか？

### ISSUE THREAD

**Issue by h6dworker** [griddb/php_client#1]
php のソースが必要なのでしょうか？

[root@bitrate php_client]# make
g++ -fPIC -std=c++0x -g -O2 -Iinclude -Isrc -I. -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -c -o src/griddb_php_client.o src/griddb_php_client.cxx
src/griddb_php_client.cxx:748:18: 致命的エラー: zend.h: そのようなファイルやディレクトリはありません
 #include "zend.h"
                  ^
コンパイルを停止しました。
make: *** [src/griddb_php_client.o] エラー 1

**Comment by h6dworker** [comment]
[root@localhost php_client]# make
g++ -shared  -o griddb_php_client.so src/Resource.o src/TimeSeriesProperties.o src/AggregationResult.o src/ContainerInfo.o src/Container.o src/Store.o src/StoreFactory.o src/PartitionController.o src/Query.o src/Row.o src/RowKeyPredicate.o src/RowSet.o src/TimestampUtils.o src/griddb_php_client.o -lpthread -lrt -lgridstore
/usr/bin/ld: -lgridstore が見つかりません
collect2: エラー: ld はステータス 1 で終了しました
make: *** [griddb_php_client.so] エラー 1

makeするにはどうしたらよいでしょうか？

**Comment by knonomura** [comment]
ご利用ありがとうございます。

>/usr/bin/ld: -lgridstore が見つかりません

本プログラムにはGridDB Cクライアントが必要になります。
GridDBのCクライアントのインストールをした上で、LIBRARY_PATHを設定してみてください。
export LIBRARY_PATH=$LIBRARY_PATH:\<C client library file directory path\>

Cクライアントについては以下の情報もご参照ください。
(ソースからのビルド方法)
https://github.com/griddb/c_client/blob/master/README_ja.md
(バイナリのある場所)
https://github.com/griddb/c_client/releases/tag/v4.0.0

**Comment by knonomura** [comment]
PHPについて：
本プログラムはCentOS 7.4、PHP7でビルドとサンプル実行の確認をしています。
既に自己解決されているようですが、PHP7のインストール方法については、
例えば以下の情報が参考になると思います。
(CentOS7 に PHP7 をインストールする方法)
https://webbibouroku.com/Blog/Article/centos-php7

よろしければ、以下の情報もご参照ください。
(GridDB PHPクライアント入門)
https://griddb.net/ja/blog/getting-started-with-the-griddb-php-client/

**Comment by h6dworker** [comment]
ありがとうございます。

お返事が遅くなり失礼いたしました。
